# Commands
alias lsa='ls -lh --group-directories-first'
alias lsaa='ls -lah --group-directories-first'
alias c='clear'
alias vi='nvim.app'
alias svi='sudo -E vim'
alias sourcer='source ~/.bashrc'
alias py='python3'
alias gb='cd ..'
alias findf='sudo find / -type f -name'
alias findd='sudo find / -type d -name'
alias lfindf='sudo find . -type f -name'
alias lfindd='sudo find . -type d -name'
alias sdn='shutdown -h now'
alias btctl='bluetoothctl'
alias asearch='apt-cache search'

# Apps
alias vd='visidata'
alias ss='xfce4-screenshooter > /dev/null 2> /dev/null &'
