#! /bin/python3
import os

USER = os.getlogin()

FilePaths = {
    '.bash_aliases': f'/home/{USER}/.bash_aliases',
    '.bash_custom': f'/home/{USER}/.bash_custom',
    '.tmux.conf': f'/home/{USER}/.tmux.conf',
    '.vimrc': f'/home/{USER}/.vimrc',
    'keybindings.json': f'/home/{USER}/.config/Code/User/keybindings.json',
    'settings.json': f'/home/{USER}/.config/Code/User/settings.json',
}

# Cache current file if it exists
if not os.path.isdir('cache'):
    os.mkdir('cache')
for _, p in FilePaths.items():
    if os.path.exists(p):
        os.rename(p, f'cache/{os.path.basename(p)}')

# Create link
for f, p in FilePaths.items():
    os.symlink(os.path.abspath(f), p)

# bash_custom
with open(f'/home/{USER}/.bashrc', 'a') as f:
    f.write('''\n\nif [ -f ~/.bash_custom ]; then\n\t. ~/.bash_custom\nfi''')

